env:
  global:
    - FRAMEWORK_NAME=RxApollo
    - secure: "Qz8sO2AcVlyh5FaKQmwhRkxZ+qWd8l9htV30RrMs7y6bPXQvbINla4qsDiEudmhXRgxmLaSLbHwAj0leuZNnUxxMf5SjlkeRtO1gARHgkxeZ+3hrq7EZdC7pIyFUQKIqMpJ65pRmxvjrWguoyh3gI08iddRWjmAa/7h0GsxaVjBwRmPbtpyYTyJM23w/Wi2bp0Yi58IBexXcag+ODNXa1f+c/Sky0b33UE1Ia+iyo5SsTzFUWosz4tiFxy/htNkIQ5q/rV4lR+IqnyLyxw1K/3z45QBXNNOZf09k9CTrjvKgpGHGA0vbDJkXvN31mXGSceXsqJ5zv6wCchyzScrT8KngMAEhMGUpKL4+0BLNnu3sEABO2Vr51MjuzuRhFq1ebdtX5G3oe/4GxUd75L9QTdHyFzRd7Ls1wbt2fVk7sfAv5tdRnhl+HdjVWU8GatxnhjaKsqlvjRXUvqhEjSsJxklO69YRItr6Dv1byDDhmGxokoccKPI6XwPCZ+zIdcpm6hnLnOid2s8Dy/atyKX/1CmFVD+tM/yH5i55sYwgZXxQYfLgDR3pPDXXs86LZtisFoDPOaCkgW8VsWFTI7e3dhOt0dzeHFdqZcEB4fD/aIKPHNqGFLN97QUgYA1k27P2EFU4XGUum83cBqpK/52mtQ4GrK+J2etNJGUBc7yxPeA="

cache:
  directories:
    - build
    - Packages
    - Carthage

script: placeholder # workaround for https://github.com/travis-ci/travis-ci/issues/4681
matrix:
  include:
    - script:
        - carthage bootstrap --platform ios --cache-builds
        - set -o pipefail && xcodebuild -scheme $FRAMEWORK_NAME -project $FRAMEWORK_NAME.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0' clean build-for-testing test | xcpretty
      env: JOB=Xcode
      os: osx
      osx_image: xcode8.3
      language: objective-c
      before_install:
        - ./scripts/upstall-carthage.sh
        - ./scripts/upstall-swiftlint.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      before_deploy:
        - carthage build --no-skip-current
        - carthage archive $FRAMEWORK_NAME
#    - script:
#        - swift test
#      env: JOB=SPM
#      os: osx
#      osx_image: xcode8.3
#      language: objective-c
#    - script:
#        - swift test
#      env: JOB=Linux
#      sudo: required
#      dist: trusty
#      language: generic
#      install:
#        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"

  exclude:
    - script: placeholder # workaround for https://github.com/travis-ci/travis-ci/issues/4681

deploy:
  provider: releases
  api_key:
    secure: XfkrGAXGJcBZ4lvwjbU6CciKKR6otWSwwph5ce7iDBM4QpiPYOWpAc/8pga5BFbutZEMlYhALbS/UqxI93aDdd7lnqvRtPH/YkxYQXaiHRGjbCkN/L3XGJ9XT750YZhSFDaTGO6fzcWUENNylLiY5b55azNIdMz3u8O2EdNoISn/Mox9RwHy6sANPTlg9POQ7b8DMYoypr888z7OZHS/VmebXONHzohMGBnMiPiWKPXtKFwB13xWxweJENgwN9pUpcCTBcC+Rkj8F8TJNTT3U2uCVuRkNcOZAEK7dmc8xVnbNzAFY+h/eeSaXxiEBVHvS4lo7ghpqjw6WZrtXLFnKt/UHfIHT7rZhtN8+8TiLENpsv32bdGRrgBBGjUYMKeEyC3RJpOuBknRW/HfOCSwGb9wio7slCX5LPUA+gvhAtg2JdLBU72QsYOSHCQPkbLE0zJuLCAYLT3FxYKkqqULq0HYAzRph/u/tCqrc9yFvvw/fqFKz+ieJnHB3LXTOXGQqZJ87vFKXTOcEJViqD3Wh1/iRnltpw+BQGOduvvU5ithsrCVwXBuh1EHs3qLKVkJmw2Jl0sxX2kVO+DQjXx5cDJGUekhqTADb5Lye/UvoROL7e+PI0mrp6zLAVHwkI9O/6EVqOtZaPqMl4V7Dz+/YztGXKAMX7tnDqMqtCiMrj8=
  file: $FRAMEWORK_NAME.framework.zip
  skip_cleanup: true
  on:
    repo: scottrhoyt/$FRAMEWORK_NAME
    tags: true
    condition: $JOB = Xcode
